### ISSUE TITLE
ECL-resultaten niet actief bijgewerkt?

### ISSUE THREAD

**Issue by hielkema** [mertenssander/nictiz_webtools#10]
Bij het oplossen van diverse QA-meldingen valt me op dat een reeks concepten die in de laatste editie inactief zijn geworden, maar nog in de ECL-queries staan, nog steeds ECL-resultaten opleveren. Dat is raar; je zou er 0 of hooguit 1 (het concept zelf) verwachten. Bijvoorbeeld 86062001 |medicatiegeïnduceerde contactdermatitis (aandoening)| in https://termservice.test-nictiz.nl/node/?#/mapping/Projects/9/Task/12830 . Het concept is inactief, maar de ECL-query < 86062001 |medicatiegeïnduceerde contactdermatitis (aandoening)| levert 17 resultaten op. Hoe kan dat? Ik dacht dat zoiets tenminste bij de nachtelijke updates bijgewerkt werd?

**Comment by mertenssander** [comment]
Die nachtelijke taak stond onterecht niet aan.. Ik heb hem weer aangezet en direct laten draaien. Als dit nog een keer gebeurt laat het me vooral weten - dit zou inderdaad niet mogen.

Voor dit soort situaties (falende ECL query) zou ook een audit hit moeten ontstaan - dit zal ik toevoegen.
